package de.kit.esmserver.uicomponents.basiccomponents;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Component;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Tree;

@SuppressWarnings("serial")
public class TreeComponent extends CustomComponent {
	public static enum Type {
		Question, Rule
	}

	private Tree tree;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TreeComponent(TreeComponent.Type type) {
		buildMainLayout(type);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout(Type type) {
		// the main layout and components will be created here
		if (type == Type.Question) {
			tree = new Tree("ESMComponents");
			tree.setDragMode(Tree.TreeDragMode.NODE);
			String itemId6 = "Questions";
			tree.addItem(itemId6);
			String itemId7 = "Open Question";
			tree.addItem(itemId7);
			tree.setParent(itemId7, itemId6);
			tree.setChildrenAllowed(itemId7, false);
			Object itemId8 = tree.addItem();
			tree.setItemCaption(itemId8, "Select One Question");
			tree.addItem(itemId8);
			tree.setParent(itemId8, itemId6);
			tree.setChildrenAllowed(itemId8, false);
			Object itemId9 =tree.addItem();
			tree.setItemCaption(itemId9, "Select Many Question");
			tree.addItem(itemId9);
			tree.setParent(itemId9, itemId6);
			tree.setChildrenAllowed(itemId9, false);
			Object itemId10 = tree.addItem();
			tree.setItemCaption(itemId10, "Likert Question");
			tree.addItem(itemId10);
			tree.setParent(itemId10, itemId6);
			tree.setChildrenAllowed(itemId10, false);
			Object itemId11 = tree.addItem();
			tree.setItemCaption(itemId11, "Slider Question");
			tree.addItem(itemId11);
			tree.setParent(itemId11, itemId6);
			tree.setChildrenAllowed(itemId11, false);
			String itemId12 = "Conditional Question";
			tree.addItem(itemId12);
			tree.setParent(itemId12, itemId6);
			Object itemId13 = tree.addItem();
			tree.setItemCaption(itemId13, "Select One Question");
			tree.addItem(itemId13);
			tree.setParent(itemId13, itemId12);
			tree.setChildrenAllowed(itemId13, false);
			Object itemId14 = tree.addItem();
			tree.setItemCaption(itemId14, "Select Many Question");
			tree.addItem(itemId14);
			tree.setParent(itemId14, itemId12);
			tree.setChildrenAllowed(itemId14, false);
			Object itemId15 = tree.addItem();
			tree.setItemCaption(itemId15, "Likert Question");
			tree.addItem(itemId15);
			tree.setParent(itemId15, itemId12);
			tree.setChildrenAllowed(itemId15, false);
			Object itemId16 = tree.addItem();
			tree.setItemCaption(itemId16, "Slider Question");
			tree.addItem(itemId16);
			tree.setParent(itemId16, itemId12);
			tree.setChildrenAllowed(itemId16, false);
			tree.expandItemsRecursively(itemId6);
		} else {
			tree = new Tree("Rules");
			tree.setDragMode(Tree.TreeDragMode.NODE);
			String itemId = "Sensors";
			tree.addItem(itemId);
			String itemId2 = "Weather";
			tree.addItem(itemId2);
			tree.setParent(itemId2, itemId);
			tree.setChildrenAllowed(itemId2, false);
			String itemId3 = "ScreenActivity";
			tree.addItem(itemId3);
			tree.setParent(itemId3, itemId);
			tree.setChildrenAllowed(itemId3, false);
			String itemId4 = "AmbientLight";
			tree.addItem(itemId4);
			tree.setParent(itemId4, itemId);
			tree.setChildrenAllowed(itemId4, false);
			String itemId5 = "Geofence";
			tree.addItem(itemId5);
			tree.setParent(itemId5, itemId);
			tree.setChildrenAllowed(itemId5, false);
			String itemId6 = "Time";
			tree.addItem(itemId6);
			tree.setParent(itemId6, itemId);
			tree.setChildrenAllowed(itemId6, false);
			String itemId7 = "UserActivity";
			tree.addItem(itemId7);
			tree.setParent(itemId7, itemId);
			tree.setChildrenAllowed(itemId7, false);
			String itemId8 = "Telephon";
			tree.addItem(itemId8);
			tree.setParent(itemId8, itemId);
			tree.setChildrenAllowed(itemId8, false);
			String itemId9 = "Notification";
			tree.addItem(itemId9);
			tree.setParent(itemId9, itemId);
			tree.setChildrenAllowed(itemId9, false);
			String itemId10 = "Bluetooth";
			tree.addItem(itemId10);
			tree.setParent(itemId10, itemId);
			tree.setChildrenAllowed(itemId10, false);
			String itemId11 = "Accelerometer";
			tree.addItem(itemId11);
			tree.setParent(itemId11, itemId);
			tree.setChildrenAllowed(itemId11, false);
			tree.expandItemsRecursively(itemId);
		}
		tree.setWidth("300");
	}

	public Component getComponent() {
		return tree;
	}

}
