package de.kit.esmserver.uicomponents.question.conditional;

import javax.xml.stream.XMLStreamException;
import javax.xml.stream.XMLStreamWriter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;

import de.kit.esmserver.uicomponents.validators.DoubleValidator;
import de.kit.esmserver.uicomponents.validators.MinMaxValidator;
import de.kit.esmserver.uicomponents.validators.MultiTextfieldRangeValidator;
import de.kit.esmserver.uicomponents.validators.NotNullValidator;

public class LikertQuestionConditionalComponent extends
		AbstractConditionalQuestion {
	private static final long serialVersionUID = -6798173105756403639L;
	protected GridLayout mainLayout;
	protected TextField textfieldValue;
	protected TextField minBoundField;
	protected TextField maxBoundField;
	protected TextField requiredBoundField;
	protected TextField minDescriptionField;
	protected TextField maxDescriptionField;
	protected DoubleValidator digitValidator;
	protected NotNullValidator notNullValidator;
	protected MinMaxValidator minMaxValidator;

	public LikertQuestionConditionalComponent() {
		digitValidator = new DoubleValidator(false, false);
		notNullValidator = new NotNullValidator();
		buildMainLayout();
	}

	@AutoGenerated
	protected Panel buildMainLayout() {
		mainLayout = new GridLayout(8, 1);

		Label labelName = new Label();
		labelName.setImmediate(true);
		labelName.setValue("Question");
		mainLayout.addComponent(labelName);

		textfieldValue = new TextField();
		textfieldValue.setImmediate(true);
		textfieldValue.setValidationVisible(true);
		textfieldValue.setWidth("120");
		textfieldValue.addValidator(notNullValidator);
		mainLayout.addComponent(textfieldValue);

		Label minBoundLabel = new Label("Min. Bound");
		minBoundLabel.setImmediate(true);
		mainLayout.addComponent(minBoundLabel);

		minBoundField = new TextField();
		minBoundField.setImmediate(true);
		minBoundField.setValidationVisible(true);
		minBoundField.setWidth("120");
		minBoundField.setValue("0");
		minBoundField.addValidator(digitValidator);
		mainLayout.addComponent(minBoundField);

		Label maxBoundLabel = new Label("Max. Bound");
		maxBoundLabel.setImmediate(true);
		mainLayout.addComponent(maxBoundLabel);

		maxBoundField = new TextField();
		maxBoundField.setImmediate(true);
		maxBoundField.setValidationVisible(true);
		maxBoundField.setWidth("120");
		maxBoundField.setValue("5");
		maxBoundField.addValidator(digitValidator);
		mainLayout.addComponent(maxBoundField);

		minMaxValidator = new MinMaxValidator(minBoundField, maxBoundField);
		maxBoundField.addValidator(minMaxValidator);
		minBoundField.addValidator(minMaxValidator);

		Label requiredBoundLabel = new Label("Required Bound");
		requiredBoundLabel.setImmediate(true);
		mainLayout.addComponent(requiredBoundLabel);

		requiredBoundField = new TextField();
		requiredBoundField.setImmediate(true);
		requiredBoundField.setValidationVisible(true);
		requiredBoundField.setWidth("120");
		requiredBoundField.setValue("3");
		requiredBoundField.addValidator(digitValidator);
		mainLayout.addComponent(requiredBoundField);

		MultiTextfieldRangeValidator muValidator = new MultiTextfieldRangeValidator(
				minBoundField, maxBoundField, requiredBoundField);
		minBoundField.addValidator(muValidator);
		maxBoundField.addValidator(muValidator);
		requiredBoundField.addValidator(muValidator);
		minBoundField.setValue("1");
		maxBoundField.setValue("6");
		requiredBoundField.setValue("3");

		mainLayout.addComponent(new Label("Min. Description"));
		minDescriptionField = new TextField();
		minDescriptionField.setImmediate(true);
		minDescriptionField.setValidationVisible(true);
		minDescriptionField.setWidth("120");
		minDescriptionField.addValidator(notNullValidator);
		mainLayout.addComponent(minDescriptionField);

		mainLayout.addComponent(new Label("Max. Description"));
		maxDescriptionField = new TextField();
		maxDescriptionField.setImmediate(true);
		maxDescriptionField.setValidationVisible(true);
		maxDescriptionField.setWidth("120");
		maxDescriptionField.addValidator(notNullValidator);
		mainLayout.addComponent(maxDescriptionField);

		condPanel = new Panel(mainLayout);
		condPanel.setCaption("Likert Question");
		verticalLayout.addComponent(condPanel);
		panel.setContent(verticalLayout);
		panel.setCaption("Conditional Question");

		return panel;
	}

	@Override
	public void writeXML(XMLStreamWriter writer) throws XMLStreamException {
		writer.writeStartElement("conditionalQuestion");
		writer.writeEmptyElement("likertQuestionConditional");
		writer.writeAttribute("name", textfieldValue.getValue());
		writer.writeAttribute("minBound", minBoundField.getValue());
		writer.writeAttribute("maxBound", maxBoundField.getValue());
		writer.writeAttribute("minDescription", minDescriptionField.getValue());
		writer.writeAttribute("maxDescription", maxDescriptionField.getValue());
		writer.writeAttribute("requiredBound", requiredBoundField.getValue());
		conditionedQuestion.writeXML(writer);
		writer.writeEndElement();
	}

	@Override
	public boolean isValid() {
		return validateFields();
	}

	private boolean validateFields() {
		return minBoundField.isValid() && maxBoundField.isValid()
				&& textfieldValue.isValid() && maxDescriptionField.isValid()
				&& minDescriptionField.isValid()
				&& requiredBoundField.isValid()
				&& conditionedQuestion.isValid();
	}
}
